package com.kehuiai.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.kehuiai.data.ThemePreset

fun ThemePreset.scheme(isDark: Boolean): ColorScheme = when (this) {
    ThemePreset.TANGERINE -> if (isDark) tangerineDarkScheme else tangerineLightScheme
    ThemePreset.FOREST -> if (isDark) forestDarkScheme else forestLightScheme
    ThemePreset.OCEAN -> if (isDark) oceanDarkScheme else oceanLightScheme
    ThemePreset.AMBER -> if (isDark) amberDarkScheme else amberLightScheme
    ThemePreset.VIOLET -> if (isDark) violetDarkScheme else violetLightScheme
    ThemePreset.ROSE -> if (isDark) roseDarkScheme else roseLightScheme
    ThemePreset.EMERALD -> if (isDark) emeraldDarkScheme else emeraldLightScheme
    ThemePreset.SAPPHIRE -> if (isDark) sapphireDarkScheme else sapphireLightScheme
}

// ============ TANGERINE ============
private val tangerineLightScheme = lightColorScheme(
    primary = Color(0xFF8F4C38),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDBD1),
    onPrimaryContainer = Color(0xFF723523),
    secondary = Color(0xFF77574E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBD1),
    onSecondaryContainer = Color(0xFF5D4037),
    tertiary = Color(0xFF6C5D2F),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF5E1A7),
    onTertiaryContainer = Color(0xFF534619),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFFF8F6),
    onBackground = Color(0xFF231917),
    surface = Color(0xFFFFF8F6),
    onSurface = Color(0xFF231917),
    surfaceVariant = Color(0xFFF5DED8),
    onSurfaceVariant = Color(0xFF53433F),
    outline = Color(0xFF85736E),
)

private val tangerineDarkScheme = darkColorScheme(
    primary = Color(0xFFFFB5A0),
    onPrimary = Color(0xFF561F0F),
    primaryContainer = Color(0xFF723523),
    onPrimaryContainer = Color(0xFFFFDBD1),
    secondary = Color(0xFFE7BDB2),
    onSecondary = Color(0xFF442A22),
    secondaryContainer = Color(0xFF5D4037),
    onSecondaryContainer = Color(0xFFFFDBD1),
    tertiary = Color(0xFFD8C58D),
    onTertiary = Color(0xFF3B2F05),
    tertiaryContainer = Color(0xFF534619),
    onTertiaryContainer = Color(0xFFF5E1A7),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A110F),
    onBackground = Color(0xFFF1DFDA),
    surface = Color(0xFF1A110F),
    onSurface = Color(0xFFF1DFDA),
    surfaceVariant = Color(0xFF53433F),
    onSurfaceVariant = Color(0xFFD8C2BC),
    outline = Color(0xFFA08C87),
)

// ============ FOREST ============
private val forestLightScheme = lightColorScheme(
    primary = Color(0xFF4C662B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCDEDA3),
    onPrimaryContainer = Color(0xFF354E16),
    secondary = Color(0xFF586249),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDCE7C8),
    onSecondaryContainer = Color(0xFF404A33),
    tertiary = Color(0xFF386663),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCECE7),
    onTertiaryContainer = Color(0xFF1F4E4B),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFF9FAEF),
    onBackground = Color(0xFF1A1C16),
    surface = Color(0xFFF9FAEF),
    onSurface = Color(0xFF1A1C16),
    surfaceVariant = Color(0xFFE1E4D5),
    onSurfaceVariant = Color(0xFF44483D),
    outline = Color(0xFF75796C),
)

private val forestDarkScheme = darkColorScheme(
    primary = Color(0xFFB1D18A),
    onPrimary = Color(0xFF1F3701),
    primaryContainer = Color(0xFF354E16),
    onPrimaryContainer = Color(0xFFCDEDA3),
    secondary = Color(0xFFBFCBAD),
    onSecondary = Color(0xFF2A331E),
    secondaryContainer = Color(0xFF404A33),
    onSecondaryContainer = Color(0xFFDCE7C8),
    tertiary = Color(0xFFA0D0CB),
    onTertiary = Color(0xFF003735),
    tertiaryContainer = Color(0xFF1F4E4B),
    onTertiaryContainer = Color(0xFFBCECE7),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    background = Color(0xFF12140E),
    onBackground = Color(0xFFE2E3D8),
    surface = Color(0xFF12140E),
    onSurface = Color(0xFFE2E3D8),
    surfaceVariant = Color(0xFF44483D),
    onSurfaceVariant = Color(0xFFC5C8BA),
    outline = Color(0xFF8F9285),
)

// ============ OCEAN ============
private val oceanLightScheme = lightColorScheme(
    primary = Color(0xFF415F91),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD6E3FF),
    onPrimaryContainer = Color(0xFF284777),
    secondary = Color(0xFF565F71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDAE2F9),
    onSecondaryContainer = Color(0xFF3E4759),
    tertiary = Color(0xFF705575),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFAD8FD),
    onTertiaryContainer = Color(0xFF573E5C),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFF9F9FF),
    onBackground = Color(0xFF191C20),
    surface = Color(0xFFF9F9FF),
    onSurface = Color(0xFF191C20),
    surfaceVariant = Color(0xFFE0E2EC),
    onSurfaceVariant = Color(0xFF44474E),
    outline = Color(0xFF74777F),
)

private val oceanDarkScheme = darkColorScheme(
    primary = Color(0xFFAAC7FF),
    onPrimary = Color(0xFF0A305F),
    primaryContainer = Color(0xFF284777),
    onPrimaryContainer = Color(0xFFD6E3FF),
    secondary = Color(0xFFBEC6DC),
    onSecondary = Color(0xFF283141),
    secondaryContainer = Color(0xFF3E4759),
    onSecondaryContainer = Color(0xFFDAE2F9),
    tertiary = Color(0xFFDDBCE0),
    onTertiary = Color(0xFF3F2844),
    tertiaryContainer = Color(0xFF573E5C),
    onTertiaryContainer = Color(0xFFFAD8FD),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    background = Color(0xFF111318),
    onBackground = Color(0xFFE2E2E9),
    surface = Color(0xFF111318),
    onSurface = Color(0xFFE2E2E9),
    surfaceVariant = Color(0xFF44474E),
    onSurfaceVariant = Color(0xFFC4C6D0),
    outline = Color(0xFF8E9099),
)

// ============ AMBER ============
private val amberLightScheme = lightColorScheme(
    primary = Color(0xFF6D5E0F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFF8E287),
    onPrimaryContainer = Color(0xFF534600),
    secondary = Color(0xFF665E40),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEEE2BC),
    onSecondaryContainer = Color(0xFF4E472A),
    tertiary = Color(0xFF43664E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC5ECCE),
    onTertiaryContainer = Color(0xFF2C4E38),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFFFF9EE),
    onBackground = Color(0xFF1E1B13),
    surface = Color(0xFFFFF9EE),
    onSurface = Color(0xFF1E1B13),
    surfaceVariant = Color(0xFFEAE2D0),
    onSurfaceVariant = Color(0xFF4B4739),
    outline = Color(0xFF7C7767),
)

private val amberDarkScheme = darkColorScheme(
    primary = Color(0xFFDBC66E),
    onPrimary = Color(0xFF3A3000),
    primaryContainer = Color(0xFF534600),
    onPrimaryContainer = Color(0xFFF8E287),
    secondary = Color(0xFFD1C6A1),
    onSecondary = Color(0xFF363016),
    secondaryContainer = Color(0xFF4E472A),
    onSecondaryContainer = Color(0xFFEEE2BC),
    tertiary = Color(0xFFA9D0B3),
    onTertiary = Color(0xFF143723),
    tertiaryContainer = Color(0xFF2C4E38),
    onTertiaryContainer = Color(0xFFC5ECCE),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    background = Color(0xFF15130B),
    onBackground = Color(0xFFE8E2D4),
    surface = Color(0xFF15130B),
    onSurface = Color(0xFFE8E2D4),
    surfaceVariant = Color(0xFF4B4739),
    onSurfaceVariant = Color(0xFFCDC6B4),
    outline = Color(0xFF969080),
)

// ============ VIOLET ============
private val violetLightScheme = lightColorScheme(
    primary = Color(0xFF7B5CCC),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE8DEFF),
    onPrimaryContainer = Color(0xFF2A0066),
    secondary = Color(0xFF6B5E7A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8DEEF),
    onSecondaryContainer = Color(0xFF362B42),
    tertiary = Color(0xFF9052A0),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD6FF),
    onTertiaryContainer = Color(0xFF460066),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFFBF8FF),
    onBackground = Color(0xFF1C1B22),
    surface = Color(0xFFFBF8FF),
    onSurface = Color(0xFF1C1B22),
    surfaceVariant = Color(0xFFE8E0EC),
    onSurfaceVariant = Color(0xFF46464F),
    outline = Color(0xFF777680),
)

private val violetDarkScheme = darkColorScheme(
    primary = Color(0xFFCDBFFF),
    onPrimary = Color(0xFF3A0066),
    primaryContainer = Color(0xFF5B3DB3),
    onPrimaryContainer = Color(0xFFE8DEFF),
    secondary = Color(0xFFD8C8E8),
    onSecondary = Color(0xFF362B42),
    secondaryContainer = Color(0xFF50425A),
    onSecondaryContainer = Color(0xFFE8DEEF),
    tertiary = Color(0xFFEFA8D8),
    onTertiary = Color(0xFF5C0066),
    tertiaryContainer = Color(0xFF7B2D7A),
    onTertiaryContainer = Color(0xFFFFD6FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    background = Color(0xFF14131A),
    onBackground = Color(0xFFE5E1EC),
    surface = Color(0xFF14131A),
    onSurface = Color(0xFFE5E1EC),
    surfaceVariant = Color(0xFF46464F),
    onSurfaceVariant = Color(0xFFC7C5D0),
    outline = Color(0xFF91909A),
)

// ============ ROSE ============
private val roseLightScheme = lightColorScheme(
    primary = Color(0xFFBA2A58),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E0),
    onPrimaryContainer = Color(0xFF5E001F),
    secondary = Color(0xFF7E5860),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9E0),
    onSecondaryContainer = Color(0xFF3B1F22),
    tertiary = Color(0xFFAD4A28),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDBC9),
    onTertiaryContainer = Color(0xFF3D0C00),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFFFF8F8),
    onBackground = Color(0xFF231919),
    surface = Color(0xFFFFF8F8),
    onSurface = Color(0xFF231919),
    surfaceVariant = Color(0xFFF5DDDF),
    onSurfaceVariant = Color(0xFF534344),
    outline = Color(0xFF857375),
)

private val roseDarkScheme = darkColorScheme(
    primary = Color(0xFFFFB0C4),
    onPrimary = Color(0xFF5E001F),
    primaryContainer = Color(0xFF961F3E),
    onPrimaryContainer = Color(0xFFFFD9E0),
    secondary = Color(0xFFECB9C2),
    onSecondary = Color(0xFF3B1F22),
    secondaryContainer = Color(0xFF533537),
    onSecondaryContainer = Color(0xFFFFD9E0),
    tertiary = Color(0xFFFFB59A),
    onTertiary = Color(0xFF5D1A00),
    tertiaryContainer = Color(0xFF7D2E14),
    onTertiaryContainer = Color(0xFFFFDBC9),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    background = Color(0xFF1A1113),
    onBackground = Color(0xFFF1DFE0),
    surface = Color(0xFF1A1113),
    onSurface = Color(0xFFF1DFE0),
    surfaceVariant = Color(0xFF534344),
    onSurfaceVariant = Color(0xFFD8C2C4),
    outline = Color(0xFFA08C8E),
)

// ============ EMERALD ============
private val emeraldLightScheme = lightColorScheme(
    primary = Color(0xFF00794C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB2F2D6),
    onPrimaryContainer = Color(0xFF002114),
    secondary = Color(0xFF4A6358),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCE8DC),
    onSecondaryContainer = Color(0xFF1E352C),
    tertiary = Color(0xFF3E6374),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC3E8F7),
    onTertiaryContainer = Color(0xFF001F2A),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFF0FAF4),
    onBackground = Color(0xFF191C1A),
    surface = Color(0xFFF0FAF4),
    onSurface = Color(0xFF191C1A),
    surfaceVariant = Color(0xFFD1E4DC),
    onSurfaceVariant = Color(0xFF3F4944),
    outline = Color(0xFF6F7974),
)

private val emeraldDarkScheme = darkColorScheme(
    primary = Color(0xFF6CDBAC),
    onPrimary = Color(0xFF003823),
    primaryContainer = Color(0xFF005234),
    onPrimaryContainer = Color(0xFFB2F2D6),
    secondary = Color(0xFFB1CCBF),
    onSecondary = Color(0xFF1E352C),
    secondaryContainer = Color(0xFF334C42),
    onSecondaryContainer = Color(0xFFCCE8DC),
    tertiary = Color(0xFFA6CDDE),
    onTertiary = Color(0xFF003545),
    tertiaryContainer = Color(0xFF254D5D),
    onTertiaryContainer = Color(0xFFC3E8F7),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    background = Color(0xFF111917),
    onBackground = Color(0xFFDFE5E0),
    surface = Color(0xFF111917),
    onSurface = Color(0xFFDFE5E0),
    surfaceVariant = Color(0xFF3F4944),
    onSurfaceVariant = Color(0xFFBFC9C3),
    outline = Color(0xFF89938D),
)

// ============ SAPPHIRE ============
private val sapphireLightScheme = lightColorScheme(
    primary = Color(0xFF1D5FA0),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD3E3FF),
    onPrimaryContainer = Color(0xFF001C37),
    secondary = Color(0xFF54687E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD9E3F5),
    onSecondaryContainer = Color(0xFF2C3E50),
    tertiary = Color(0xFF6E5684),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF7D8FF),
    onTertiaryContainer = Color(0xFF351A4A),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFF8F9FF),
    onBackground = Color(0xFF191C20),
    surface = Color(0xFFF8F9FF),
    onSurface = Color(0xFF191C20),
    surfaceVariant = Color(0xFFD9E2EC),
    onSurfaceVariant = Color(0xFF44474E),
    outline = Color(0xFF74777F),
)

private val sapphireDarkScheme = darkColorScheme(
    primary = Color(0xFFA5C9FF),
    onPrimary = Color(0xFF00315C),
    primaryContainer = Color(0xFF004884),
    onPrimaryContainer = Color(0xFFD3E3FF),
    secondary = Color(0xFFBCC6D8),
    onSecondary = Color(0xFF2C3E50),
    secondaryContainer = Color(0xFF435666),
    onSecondaryContainer = Color(0xFFD9E3F5),
    tertiary = Color(0xFFDBB9EE),
    onTertiary = Color(0xFF4B2D66),
    tertiaryContainer = Color(0xFF62447D),
    onTertiaryContainer = Color(0xFFF7D8FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    background = Color(0xFF111318),
    onBackground = Color(0xFFE2E2E9),
    surface = Color(0xFF111318),
    onSurface = Color(0xFFE2E2E9),
    surfaceVariant = Color(0xFF44474E),
    onSurfaceVariant = Color(0xFFC4C6D0),
    outline = Color(0xFF8E9099),
)
