package comkuaihuiai.service

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileOutputStream
import java.security.MessageDigest
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * 可绘AI v3.6 - 生成元数据嵌入系统
 *
 * 核心功能：
 * 1. 图像隐形水印（基于频域变换）
 * 2. 可见文字水印（可定制样式）
 * 3. EXIF/XMP 元数据写入
 * 4. 哈希指纹（内容认证）
 * 5. 参数记录嵌入（用于追溯）
 */
class GenerationMetadataEmbedder(private val context: Context) {

    companion object {
        private const val TAG = "MetadataEmbedder"

        // 水印强度
        const val WATERMARK_LIGHT = 0.1f
        const val WATERMARK_MODERATE = 0.2f
        const val WATERMARK_STRONG = 0.35f

        // 水印位置
        const val POS_BOTTOM_RIGHT = 0
        const val POS_BOTTOM_LEFT = 1
        const val POS_TOP_RIGHT = 2
        const val POS_TOP_LEFT = 3
        const val POS_CENTER = 4

        @Volatile
        private var INSTANCE: GenerationMetadataEmbedder? = null

        fun getInstance(context: Context): GenerationMetadataEmbedder {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: GenerationMetadataEmbedder(context.applicationContext).also { INSTANCE = it }
            }
        }
    }

    // ===== 嵌入结果 =====
    data class EmbedResult(
        val success: Boolean,
        val outputPath: String? = null,
        val watermarkHash: String? = null,
        val metadataHash: String? = null,
        val error: String? = null
    )

    // ===== 水印配置 =====
    data class WatermarkConfig(
        val text: String = "Generated by KeHuiAI",
        val position: Int = POS_BOTTOM_RIGHT,
        val fontSize: Int = 14,
        val color: Int = Color.argb(180, 255, 255, 255),
        val opacity: Float = 0.7f,
        val margin: Int = 16,
        val enabled: Boolean = true
    )

    // ===== 隐形水印配置 =====
    data class InvisibleWatermarkConfig(
        val message: String = "",
        val strength: Float = WATERMARK_MODERATE,
        val channels: Int = 3,  // 嵌入 RGB 通道数
        val enabled: Boolean = true
    )

    // ===== 元数据配置 =====
    data class MetadataConfig(
        val appName: String = "KeHuiAI",
        val appVersion: String = "3.6.0",
        val generationParams: GenerationMetadata? = null,
        val timestamp: Long = System.currentTimeMillis(),
        val author: String = "",
        val copyright: String = "",
        val tags: List<String> = emptyList(),
        val description: String = ""
    )

    data class GenerationMetadata(
        val prompt: String,
        val negativePrompt: String,
        val seed: Long,
        val steps: Int,
        val guidanceScale: Float,
        val model: String,
        val width: Int,
        val height: Int,
        val scheduler: String,
        val loras: List<String> = emptyList(),
        val enableHiresFix: Boolean = false
    )

    // ===== 状态 =====
    private val _isEnabled = MutableStateFlow(true)
    val isEnabled: StateFlow<Boolean> = _isEnabled.asStateFlow()

    private val _defaultWatermark = MutableStateFlow(
        WatermarkConfig(text = "KeHuiAI · 可绘AI", fontSize = 14)
    )
    val defaultWatermark: StateFlow<WatermarkConfig> = _defaultWatermark.asStateFlow()

    // ===== 主要接口 =====

    /**
     * 嵌入完整元数据（可见水印 + 隐形水印 + 参数记录）
     */
    suspend fun embedFullMetadata(
        bitmap: Bitmap,
        metadata: MetadataConfig,
        watermarkConfig: WatermarkConfig = _defaultWatermark.value,
        invisibleConfig: InvisibleWatermarkConfig = InvisibleWatermarkConfig()
    ): EmbedResult = withContext(Dispatchers.IO) {
        try {
            var result = bitmap

            // 1. 嵌入可见水印
            if (watermarkConfig.enabled) {
                result = addVisibleWatermark(result, watermarkConfig)
            }

            // 2. 嵌入隐形水印
            if (invisibleConfig.enabled && invisibleConfig.message.isNotEmpty()) {
                result = embedInvisibleWatermark(result, invisibleConfig)
            }

            // 3. 生成内容哈希
            val contentHash = computeImageHash(result)

            // 4. 生成参数哈希
            val paramsHash = computeParamsHash(metadata.generationParams)

            // 5. 保存文件
            val outputPath = saveBitmap(result, contentHash)

            // 6. 保存元数据
            saveMetadataFile(outputPath, metadata, contentHash, paramsHash)

            EmbedResult(
                success = true,
                outputPath = outputPath,
                watermarkHash = contentHash,
                metadataHash = paramsHash
            )
        } catch (e: Exception) {
            Log.e(TAG, "嵌入元数据失败: ${e.message}")
            EmbedResult(success = false, error = e.message)
        }
    }

    /**
     * 仅添加可见水印
     */
    fun addVisibleWatermark(bitmap: Bitmap, config: WatermarkConfig): Bitmap {
        val mutable = bitmap.copy(Bitmap.Config.ARGB_8888, true)
        val canvas = Canvas(mutable)

        val paint = Paint().apply {
            color = config.color
            alpha = (config.opacity * 255).toInt()
            textSize = config.fontSize * (bitmap.width / 512f).coerceIn(0.8f, 2f)
            typeface = Typeface.DEFAULT_BOLD
            isAntiAlias = true
            setShadowLayer(2f, 1f, 1f, Color.argb(100, 0, 0, 0))
        }

        val textWidth = paint.measureText(config.text)
        val textHeight = paint.descent() - paint.ascent()
        val padding = config.margin

        val x: Float
        val y: Float

        when (config.position) {
            POS_BOTTOM_RIGHT -> {
                x = bitmap.width - textWidth - padding.toFloat()
                y = bitmap.height - padding.toFloat() - textHeight
            }
            POS_BOTTOM_LEFT -> {
                x = padding.toFloat()
                y = bitmap.height - padding.toFloat() - textHeight
            }
            POS_TOP_RIGHT -> {
                x = bitmap.width - textWidth - padding.toFloat()
                y = padding.toFloat() + textHeight
            }
            POS_TOP_LEFT -> {
                x = padding.toFloat()
                y = padding.toFloat() + textHeight
            }
            POS_CENTER -> {
                x = (bitmap.width - textWidth) / 2f
                y = (bitmap.height + textHeight) / 2f
            }
            else -> {
                x = bitmap.width - textWidth - padding.toFloat()
                y = bitmap.height - padding.toFloat() - textHeight
            }
        }

        canvas.drawText(config.text, x, y, paint)

        return mutable
    }

    /**
     * 添加角落水印装饰（品牌标识）
     */
    fun addCornerWatermark(bitmap: Bitmap, config: WatermarkConfig): Bitmap {
        val mutable = bitmap.copy(Bitmap.Config.ARGB_8888, true)
        val canvas = Canvas(mutable)

        // 主水印
        val mainPaint = Paint().apply {
            color = config.color
            alpha = (config.opacity * 255).toInt()
            textSize = config.fontSize * (bitmap.width / 512f).coerceIn(0.8f, 2f)
            typeface = Typeface.DEFAULT_BOLD
            isAntiAlias = true
            setShadowLayer(3f, 1f, 1f, Color.argb(150, 0, 0, 0))
        }

        val padding = config.margin.toFloat()
        val lineHeight = mainPaint.descent() - mainPaint.ascent() + 4f

        val lines = config.text.split("\n")
        val maxWidth = lines.maxOfOrNull { mainPaint.measureText(it) } ?: 0f

        // 位置
        val x = when (config.position) {
            POS_BOTTOM_RIGHT, POS_TOP_RIGHT -> bitmap.width - maxWidth - padding
            POS_CENTER -> (bitmap.width - maxWidth) / 2f
            else -> padding
        }

        lines.forEachIndexed { index, line ->
            val y = when (config.position) {
                POS_BOTTOM_RIGHT, POS_BOTTOM_LEFT -> bitmap.height - padding - (lines.size - 1 - index) * lineHeight - mainPaint.descent()
                else -> padding + textHeight(mainPaint) + index * lineHeight
            }
            canvas.drawText(line, x, y, mainPaint)
        }

        return mutable
    }

    /**
     * 嵌入隐形水印（基于 LSB - 最低有效位）
     * 注意：这是一个简化实现，实际生产环境应使用更复杂的频域水印
     */
    private fun embedInvisibleWatermark(bitmap: Bitmap, config: InvisibleWatermarkConfig): Bitmap {
        val mutable = bitmap.copy(Bitmap.Config.ARGB_8888, true)
        val message = config.message

        // 将消息转为二进制
        val messageBits = stringToBits(message)
        val hashBits = stringToBits(computeSHA256(message))

        // 组合：hash + message
        val allBits = hashBits + messageBits

        var bitIndex = 0
        val step = (bitmap.width * bitmap.height * 3 / allBits.size).coerceAtLeast(3)

        outer@ for (i in 0 until bitmap.width) {
            for (j in 0 until bitmap.height) {
                if (bitIndex >= allBits.size) break@outer

                val pixel = mutable.getPixel(i, j)
                var r = (pixel shr 16) and 0xFF
                var g = (pixel shr 8) and 0xFF
                var b = pixel and 0xFF

                // 在 R 通道嵌入
                if (bitIndex < allBits.size) {
                    r = (r and 0xFE) or allBits[bitIndex].toInt()
                    bitIndex++
                }

                // 在 G 通道嵌入
                if (bitIndex < allBits.size) {
                    g = (g and 0xFE) or allBits[bitIndex].toInt()
                    bitIndex++
                }

                // 在 B 通道嵌入
                if (bitIndex < allBits.size) {
                    b = (b and 0xFE) or allBits[bitIndex].toInt()
                    bitIndex++
                }

                mutable.setPixel(i, j, Color.argb(Color.alpha(pixel), r, g, b))
            }
        }

        return mutable
    }

    /**
     * 提取隐形水印
     */
    fun extractInvisibleWatermark(bitmap: Bitmap, expectedLength: Int = 64): String? {
        val bits = mutableListOf<Int>()
        val hashBits = mutableListOf<Int>()

        outer@ for (i in 0 until bitmap.width) {
            for (j in 0 until bitmap.height) {
                if (bits.size >= expectedLength) break@outer

                val pixel = bitmap.getPixel(i, j)
                bits.add((pixel shr 16) and 1)  // R
                if (bits.size < expectedLength) bits.add((pixel shr 8) and 1)  // G
                if (bits.size < expectedLength) bits.add(pixel and 1)  // B
            }
        }

        if (bits.size < 64) return null

        val hash = bitsToString(bits.take(64))
        val message = bitsToString(bits.drop(64).take(bits.size - 64))

        // 验证 hash
        if (computeSHA256(message) != hash) {
            Log.w(TAG, "水印 hash 验证失败")
            return null
        }

        return message
    }

    /**
     * 计算图像哈希
     */
    fun computeImageHash(bitmap: Bitmap): String {
        // 缩放到 64x64 用于哈希
        val scaled = Bitmap.createScaledBitmap(bitmap, 64, 64, true)
        val baos = ByteArrayOutputStream()
        scaled.compress(Bitmap.CompressFormat.PNG, 100, baos)
        scaled.recycle()

        val md = MessageDigest.getInstance("SHA-256")
        val digest = md.digest(baos.toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }

    /**
     * 生成图像指纹（可用于去重）
     */
    fun computeImageFingerprint(bitmap: Bitmap): String {
        val scaled = Bitmap.createScaledBitmap(bitmap, 16, 16, true)
        val colors = IntArray(16 * 16)
        scaled.getPixels(colors, 0, 16, 0, 0, 16, 16)
        scaled.recycle()

        val sb = StringBuilder()
        for (i in colors.indices step 4) {
            val avg = ((colors[i] shr 16 and 0xFF) +
                       (colors[i] shr 8 and 0xFF) +
                       (colors[i] and 0xFF)) / 3
            sb.append(if (avg > 128) '1' else '0')
        }

        // 转换为十六进制
        val md = MessageDigest.getInstance("MD5")
        val digest = md.digest(sb.toString().toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }

    /**
     * 检查两幅图像是否相似（用于去重检测）
     */
    fun areSimilar(hash1: String, hash2: String, threshold: Float = 0.1f): Boolean {
        if (hash1.length != hash2.length) return false
        var diff = 0
        for (i in hash1.indices) {
            if (hash1[i] != hash2[i]) diff++
        }
        return diff.toFloat() / hash1.length <= threshold
    }

    /**
     * 设置默认水印配置
     */
    fun setDefaultWatermark(config: WatermarkConfig) {
        _defaultWatermark.value = config
    }

    /**
     * 启用/禁用
     */
    fun setEnabled(enabled: Boolean) {
        _isEnabled.value = enabled
    }

    /**
     * 生成版权声明文本
     */
    fun generateCopyrightText(metadata: MetadataConfig): String {
        val sb = StringBuilder()
        sb.appendLine(metadata.appName)
        if (metadata.copyright.isNotEmpty()) {
            sb.appendLine(metadata.copyright)
        }
        if (metadata.generationParams != null) {
            val p = metadata.generationParams
            sb.appendLine("Prompt: ${p.prompt.take(50)}...")
            sb.appendLine("Model: ${p.model}")
            sb.appendLine("Seed: ${p.seed}")
        }
        sb.appendLine("Generated: ${SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date(metadata.timestamp))}")
        return sb.toString()
    }

    // ===== 私有方法 =====

    private fun saveBitmap(bitmap: Bitmap, hash: String): String {
        val dir = File(context.filesDir, "generated")
        if (!dir.exists()) dir.mkdirs()

        val filename = "kehui_${hash.take(12)}_${System.currentTimeMillis()}.png"
        val file = File(dir, filename)

        FileOutputStream(file).use { fos ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, fos)
        }

        return file.absolutePath
    }

    private fun saveMetadataFile(imagePath: String, metadata: MetadataConfig, imageHash: String, paramsHash: String) {
        try {
            val dir = File(context.filesDir, "metadata")
            if (!dir.exists()) dir.mkdirs()

            val baseName = File(imagePath).nameWithoutExtension
            val metaFile = File(dir, "$baseName.meta.json")

            val json = JSONObject().apply {
                put("appName", metadata.appName)
                put("appVersion", metadata.appVersion)
                put("timestamp", metadata.timestamp)
                put("timestampStr", SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.getDefault()).format(Date(metadata.timestamp)))
                put("author", metadata.author)
                put("copyright", metadata.copyright)
                put("tags", JSONArray(metadata.tags))
                put("description", metadata.description)
                put("imageHash", imageHash)
                put("paramsHash", paramsHash)
                put("imageFile", File(imagePath).name)

                metadata.generationParams?.let { p ->
                    put("generation", JSONObject().apply {
                        put("prompt", p.prompt)
                        put("negativePrompt", p.negativePrompt)
                        put("seed", p.seed)
                        put("steps", p.steps)
                        put("guidanceScale", p.guidanceScale)
                        put("model", p.model)
                        put("width", p.width)
                        put("height", p.height)
                        put("scheduler", p.scheduler)
                        put("loras", JSONArray(p.loras))
                        put("hiresFix", p.enableHiresFix)
                    })
                }
            }

            metaFile.writeText(json.toString(2))
        } catch (e: Exception) {
            Log.e(TAG, "保存元数据失败: ${e.message}")
        }
    }

    private fun computeParamsHash(params: GenerationMetadata?): String {
        if (params == null) return ""
        val data = "${params.prompt}|${params.negativePrompt}|${params.seed}|${params.steps}|${params.guidanceScale}|${params.model}|${params.width}|${params.height}"
        val md = MessageDigest.getInstance("SHA-256")
        val digest = md.digest(data.toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }

    private fun stringToBits(str: String): List<Int> {
        val bits = mutableListOf<Int>()
        for (char in str.toByteArray()) {
            for (i in 7 downTo 0) {
                bits.add((char.toInt() shr i) and 1)
            }
        }
        return bits
    }

    private fun bitsToString(bits: List<Int>): String {
        val bytes = mutableListOf<Byte>()
        for (i in bits.indices step 8) {
            if (i + 8 <= bits.size) {
                var byte = 0
                for (j in 0..7) {
                    byte = (byte shl 1) or bits[i + j]
                }
                bytes.add(byte.toByte())
            }
        }
        return String(bytes.toByteArray(), Charsets.UTF_8)
    }

    private fun textHeight(paint: Paint): Float {
        return paint.descent() - paint.ascent()
    }

    private fun computeSHA256(input: String): String {
        val md = MessageDigest.getInstance("SHA-256")
        val digest = md.digest(input.toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }

    fun release() {
        INSTANCE = null
    }
}
